I added a new class pollingWorker in a new thread that prints values of parameters to the terminal at rates specified in the config file
toolsforexperiments/instrumentserver pull request #88
Opened 2024-03-22 17:06 UTC by JonathanNolan3

2024-03-25 21:34 UTC, marcosfrenkel requested changes

2024-03-25 21:34 UTC, marcosfrenkel commented on instrumentserver/apps.py
> +from .server.pollingWorker import pollingWorker
add a white-space between imports and code

2024-03-25 21:34 UTC, marcosfrenkel commented on instrumentserver/apps.py
> +def quitPollingThread():
add a '_' at the beginning of the function name. This indicates that this is a "private" method and users should not use this function. Should look like `_quitPollingThread`

2024-03-25 22:41 UTC, JonathanNolan3 commented on instrumentserver/server/core.py
> +        from ..apps import quitPollingThread
Note: Causes circular import if placed at the beginning of the file

2024-03-27 19:51 UTC, marcosfrenkel requested changes

2024-03-27 19:51 UTC, marcosfrenkel commented on instrumentserver/config.py
> +            if pollingRateList != None:
change the != for `is not`. When dealing with `None` that is a better way of doing that comparison in python

2024-03-27 19:51 UTC, marcosfrenkel commented on instrumentserver/apps.py
>          # Separates the corresponding settings into the 4 necessary parts
into the 5 necessary parts

2024-03-27 19:51 UTC, marcosfrenkel commented on instrumentserver/server/pollingWorker.py
> +                logger.warn(f"Parameter {param} does not exist")
The warn method is deprecated, use warning instead

2024-03-27 19:53 UTC, marcosfrenkel commented
I have added a few more cosmetic changes that I found when I was looking over the code again. 

I still think there should be a way of avoiding that import in the middle of the code. Let me see if I can figure some workaround

2024-04-16 18:09 UTC, marcosfrenkel requested changes

2024-04-16 18:09 UTC, marcosfrenkel commented on instrumentserver/server/core.py
> +        _quitPollingThread()
This should be removed right? it is not needed anymore now that we are passing the thread as an argument?

2024-04-16 18:09 UTC, marcosfrenkel commented on instrumentserver/apps.py
> +    serverScript.pollingThread = QtCore.QThread()
We should probably have this only start if the user passes a polling rate. But we can have that as an issue for now if its too hard

2024-04-16 18:43 UTC, marcosfrenkel commented on instrumentserver/apps.py
> +    pollingThread = QtCore.QThread()
Add an if that thins only happens if pollinRates is not None, no need to start a new polling thread if no polling is accepted.

2024-04-16 18:43 UTC, marcosfrenkel commented on instrumentserver/server/core.py
> +                 pthread: Any = None
rename it pollingThread

2024-04-16 18:44 UTC, marcosfrenkel requested changes
last things and this is ready for merging

2024-07-17 18:26 UTC, merged